### ISSUE TITLE
Syntax error on various places

### ISSUE THREAD

**Issue by dvliman** [maccman/spine.rails3#1]
There are some syntax errors in some files, for example: 

spine.rails3/config/initializers/session_store.rb:3: syntax error, unexpected ':', expecting $end (SyntaxError)
...sion_store :cookie_store, key: '_spine.rails3_session'

where it should have been 
 `:key => '_spine.rails3_session`'

if @page.save
      respond_with(@page, status: :created, location: @page)

`status: :created`

I see similar errors in some other files (in controller, views...)

I am quite new to ruby (and therefore rails). Is this some new rails / ruby feature that I am not aware of? 

Thanks

**Comment by maccman** [comment]
You're using an old version of Ruby, you need to use Ruby 1.9.2
