### ISSUE TITLE
Back button doesn't work

### ISSUE THREAD

**Issue by christianvuerings** [maccman/spine.rails3#3]
Tested in latest Google Chrome on OS X

1) Go to http://spine-rails3.herokuapp.com/
2) Click on a page (show link)
3) Click on the browser's back button

Expected: go to previous page
What happens: Stay on the same page

**Comment by maccman** [comment]
Actually fixed, just didn't deploy. Thanks!

**Comment by christianvuerings** [comment]
Thanks for the quick reply.
